---
# tasks file for test_role
#
  - name: Set version
    ansible.builtin.set_fact:
      fact: "20241112T195659297605"

  - name: Print version
    ansible.builtin.debug:
      msg: "{{ fact }}"

  - name: Set executed timestamp stat
    ansible.builtin.set_stats:
      data:
        execution_timestamp: "{{ fact }}"


