---
# tasks file for test_role
#
  - name: Set version
    ansible.builtin.set_fact:
      fact: "20241109T183332379092"

  - name: Set version with job_uuid prefix
      "b3f1189d-291c-411f-9974-d434947ee15b_fact: "20241109T191620262378"
      "{{ job_uuid }}_fact": "20241109T181754903609"

  - name: Print version
    ansible.builtin.debug:
      msg: "{{ hostvars.localhost['{{ job_uuid }}_fact'] }}"

  - name: Set executed timestamp stat with job_uuid prefix
    ansible.builtin.set_stats:
      data:
      "{{ job_uuid }}_execution_timestamp": "{{ hostvars.localhost['{{ job_uuid }}_fact'] }}"
