---
# tasks file for test_role
#
  - name: Set version
    ansible.builtin.set_fact:
      "f40f6db0-ad3f-401b-a441-7312524d91c7_fact: "20241109T191902319451"

  - name: Set version with job_uuid prefix
      ansible.builtin.set_fact:
      "{{ job_uuid }}_fact": "20241109T181754903609"

  - name: Print version
    ansible.builtin.debug:
      msg: "{{ hostvars.localhost['{{ job_uuid }}_fact'] }}"

  - name: Set executed timestamp stat with job_uuid prefix
    ansible.builtin.set_stats:
      data:
      "{{ job_uuid }}_execution_timestamp": "{{ hostvars.localhost['{{ job_uuid }}_fact'] }}"
